// GENERATED by scripts/gen-theme-registry.mjs. Do not edit by hand.
// Regenerated once per batch by the orchestrator (Lane 2 fill-out).
import type { BrandTheme } from "./types";
import neutral from "./neutral";
import t_airbnb from "./airbnb";
import t_airtable from "./airtable";
import t_apple from "./apple";
import t_binance from "./binance";
import t_bmw from "./bmw";
import t_bmw_m from "./bmw-m";
import t_bugatti from "./bugatti";
import t_cal from "./cal";
import t_claude from "./claude";
import t_clay from "./clay";
import t_clickhouse from "./clickhouse";
import t_cohere from "./cohere";
import t_coinbase from "./coinbase";
import t_composio from "./composio";
import t_cursor from "./cursor";
import t_elevenlabs from "./elevenlabs";
import t_expo from "./expo";
import t_ferrari from "./ferrari";
import t_figma from "./figma";
import t_framer from "./framer";
import t_hashicorp from "./hashicorp";
import t_ibm from "./ibm";
import t_intercom from "./intercom";
import t_kraken from "./kraken";
import t_lamborghini from "./lamborghini";
import t_linear_app from "./linear-app";
import t_lovable from "./lovable";
import t_mastercard from "./mastercard";
import t_meta from "./meta";
import t_minimax from "./minimax";
import t_mintlify from "./mintlify";
import t_miro from "./miro";
import t_mistral_ai from "./mistral-ai";
import t_mongodb from "./mongodb";
import t_nike from "./nike";
import t_notion from "./notion";
import t_nvidia from "./nvidia";
import t_ollama from "./ollama";
import t_opencode_ai from "./opencode-ai";
import t_pinterest from "./pinterest";
import t_playstation from "./playstation";
import t_posthog from "./posthog";
import t_raycast from "./raycast";
import t_renault from "./renault";
import t_replicate from "./replicate";
import t_resend from "./resend";
import t_revolut from "./revolut";
import t_runwayml from "./runwayml";
import t_sanity from "./sanity";
import t_sentry from "./sentry";
import t_shopify from "./shopify";
import t_slack from "./slack";
import t_spacex from "./spacex";
import t_spotify from "./spotify";
import t_starbucks from "./starbucks";
import t_stripe from "./stripe";
import t_supabase from "./supabase";
import t_superhuman from "./superhuman";
import t_tesla from "./tesla";
import t_theverge from "./theverge";
import t_together_ai from "./together-ai";
import t_uber from "./uber";
import t_vercel from "./vercel";
import t_vodafone from "./vodafone";
import t_voltagent from "./voltagent";
import t_warp from "./warp";
import t_webflow from "./webflow";
import t_wired from "./wired";
import t_wise from "./wise";
import t_x_ai from "./x-ai";
import t_zapier from "./zapier";

export const themes: Record<string, BrandTheme> = {
  "airbnb": t_airbnb,
  "airtable": t_airtable,
  "apple": t_apple,
  "binance": t_binance,
  "bmw": t_bmw,
  "bmw-m": t_bmw_m,
  "bugatti": t_bugatti,
  "cal": t_cal,
  "claude": t_claude,
  "clay": t_clay,
  "clickhouse": t_clickhouse,
  "cohere": t_cohere,
  "coinbase": t_coinbase,
  "composio": t_composio,
  "cursor": t_cursor,
  "elevenlabs": t_elevenlabs,
  "expo": t_expo,
  "ferrari": t_ferrari,
  "figma": t_figma,
  "framer": t_framer,
  "hashicorp": t_hashicorp,
  "ibm": t_ibm,
  "intercom": t_intercom,
  "kraken": t_kraken,
  "lamborghini": t_lamborghini,
  "linear-app": t_linear_app,
  "lovable": t_lovable,
  "mastercard": t_mastercard,
  "meta": t_meta,
  "minimax": t_minimax,
  "mintlify": t_mintlify,
  "miro": t_miro,
  "mistral-ai": t_mistral_ai,
  "mongodb": t_mongodb,
  "nike": t_nike,
  "notion": t_notion,
  "nvidia": t_nvidia,
  "ollama": t_ollama,
  "opencode-ai": t_opencode_ai,
  "pinterest": t_pinterest,
  "playstation": t_playstation,
  "posthog": t_posthog,
  "raycast": t_raycast,
  "renault": t_renault,
  "replicate": t_replicate,
  "resend": t_resend,
  "revolut": t_revolut,
  "runwayml": t_runwayml,
  "sanity": t_sanity,
  "sentry": t_sentry,
  "shopify": t_shopify,
  "slack": t_slack,
  "spacex": t_spacex,
  "spotify": t_spotify,
  "starbucks": t_starbucks,
  "stripe": t_stripe,
  "supabase": t_supabase,
  "superhuman": t_superhuman,
  "tesla": t_tesla,
  "theverge": t_theverge,
  "together-ai": t_together_ai,
  "uber": t_uber,
  "vercel": t_vercel,
  "vodafone": t_vodafone,
  "voltagent": t_voltagent,
  "warp": t_warp,
  "webflow": t_webflow,
  "wired": t_wired,
  "wise": t_wise,
  "x-ai": t_x_ai,
  "zapier": t_zapier,
};

export const builtThemeSlugs: readonly string[] = ["airbnb","airtable","apple","binance","bmw","bmw-m","bugatti","cal","claude","clay","clickhouse","cohere","coinbase","composio","cursor","elevenlabs","expo","ferrari","figma","framer","hashicorp","ibm","intercom","kraken","lamborghini","linear-app","lovable","mastercard","meta","minimax","mintlify","miro","mistral-ai","mongodb","nike","notion","nvidia","ollama","opencode-ai","pinterest","playstation","posthog","raycast","renault","replicate","resend","revolut","runwayml","sanity","sentry","shopify","slack","spacex","spotify","starbucks","stripe","supabase","superhuman","tesla","theverge","together-ai","uber","vercel","vodafone","voltagent","warp","webflow","wired","wise","x-ai","zapier"];

export function themeFor(slug: string): BrandTheme {
  return themes[slug] ?? neutral;
}

export function hasTheme(slug: string): boolean {
  return slug in themes;
}
